/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FlowImport } from './routes/flow'
import { Route as IndexImport } from './routes/index'
import { Route as FlowNewImport } from './routes/flow.new'
import { Route as FlowIdEditImport } from './routes/flow.$id.edit'

// Create/Update Routes

const FlowRoute = FlowImport.update({
  path: '/flow',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FlowNewRoute = FlowNewImport.update({
  path: '/new',
  getParentRoute: () => FlowRoute,
} as any)

const FlowIdEditRoute = FlowIdEditImport.update({
  path: '/$id/edit',
  getParentRoute: () => FlowRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flow': {
      preLoaderRoute: typeof FlowImport
      parentRoute: typeof rootRoute
    }
    '/flow/new': {
      preLoaderRoute: typeof FlowNewImport
      parentRoute: typeof FlowImport
    }
    '/flow/$id/edit': {
      preLoaderRoute: typeof FlowIdEditImport
      parentRoute: typeof FlowImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FlowRoute.addChildren([FlowNewRoute, FlowIdEditRoute]),
])

/* prettier-ignore-end */
